services:
  - type: web
    name: corner-click-api
    env: node
    plan: free
    buildCommand: npx turbo run build --filter=api...
    startCommand: node apps/api/dist/index.js
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
